### ISSUE TITLE
NPM reports vulnerability during installation

### ISSUE THREAD

**Issue by bikathi** [ctfdavis/v-slick-carousel#41]
Hi, I am attempting to use this package in one of my Nuxt app and NPM reports a vulnerability with it. When I run `npm run audit`, this is what I get. 

```
lodash.pick  >=4.0.0
Severity: high
Prototype Pollution in lodash - https://github.com/advisories/GHSA-p6mc-m468-83gw
No fix available
node_modules/lodash.pick
  v-slick-carousel  *
  Depends on vulnerable versions of lodash.pick
  node_modules/v-slick-carousel

2 high severity vulnerabilities
```

As it says no fix available, I can't use the npm-related fix command.

**Comment by ctfdavis** [comment]
Hi @bikathi ,

Thanks for raising this issue. I have looked into the problem and identified that the "lodash.pick" package causes the warning you reported as it has a security issue identified in [Github Advisory](https://github.com/advisories/GHSA-p6mc-m468-83gw). So far there is no patch to the package which would fix the issue which is why it said no fix available. Fortunately, this vulnerability should not have an actual impact because it poses a threat if "property identifiers are user-supplied" which isn't the case in VSlickCarousel. 

Nonetheless, after reviewing its usage (only three uses in [props.ts](https://github.com/ctfdavis/v-slick-carousel/blob/main/packages/v-slick-carousel/lib/components/props.ts#L100)), I think it is possible replace it with a custom method instead.
